// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: interaction.proto

package interactionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVideoInteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoInteractionRequest) Reset() {
	*x = GetVideoInteractionRequest{}
	mi := &file_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoInteractionRequest) ProtoMessage() {}

func (x *GetVideoInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoInteractionRequest.ProtoReflect.Descriptor instead.
func (*GetVideoInteractionRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoInteractionRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *GetVideoInteractionRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type GetBulkInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIds      []string               `protobuf:"bytes,1,rep,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkInteractionsRequest) Reset() {
	*x = GetBulkInteractionsRequest{}
	mi := &file_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkInteractionsRequest) ProtoMessage() {}

func (x *GetBulkInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkInteractionsRequest.ProtoReflect.Descriptor instead.
func (*GetBulkInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetBulkInteractionsRequest) GetVideoIds() []string {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

func (x *GetBulkInteractionsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type GetBulkInteractionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interactions  []*VideoInteraction    `protobuf:"bytes,1,rep,name=interactions,proto3" json:"interactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkInteractionsResponse) Reset() {
	*x = GetBulkInteractionsResponse{}
	mi := &file_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkInteractionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkInteractionsResponse) ProtoMessage() {}

func (x *GetBulkInteractionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkInteractionsResponse.ProtoReflect.Descriptor instead.
func (*GetBulkInteractionsResponse) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetBulkInteractionsResponse) GetInteractions() []*VideoInteraction {
	if x != nil {
		return x.Interactions
	}
	return nil
}

type VideoInteraction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	BookmarkCount int64                  `protobuf:"varint,4,opt,name=bookmark_count,json=bookmarkCount,proto3" json:"bookmark_count,omitempty"`
	ViewCount     int64                  `protobuf:"varint,5,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,6,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	IsBookmarked  bool                   `protobuf:"varint,7,opt,name=is_bookmarked,json=isBookmarked,proto3" json:"is_bookmarked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInteraction) Reset() {
	*x = VideoInteraction{}
	mi := &file_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInteraction) ProtoMessage() {}

func (x *VideoInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInteraction.ProtoReflect.Descriptor instead.
func (*VideoInteraction) Descriptor() ([]byte, []int) {
	return file_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *VideoInteraction) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoInteraction) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoInteraction) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoInteraction) GetBookmarkCount() int64 {
	if x != nil {
		return x.BookmarkCount
	}
	return 0
}

func (x *VideoInteraction) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *VideoInteraction) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *VideoInteraction) GetIsBookmarked() bool {
	if x != nil {
		return x.IsBookmarked
	}
	return false
}

var File_interaction_proto protoreflect.FileDescriptor

const file_interaction_proto_rawDesc = "" +
	"\n" +
	"\x11interaction.proto\x12\vinteraction\"a\n" +
	"\x1aGetVideoInteractionRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"c\n" +
	"\x1aGetBulkInteractionsRequest\x12\x1b\n" +
	"\tvideo_ids\x18\x01 \x03(\tR\bvideoIds\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"`\n" +
	"\x1bGetBulkInteractionsResponse\x12A\n" +
	"\finteractions\x18\x01 \x03(\v2\x1d.interaction.VideoInteractionR\finteractions\"\xf7\x01\n" +
	"\x10VideoInteraction\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x03 \x01(\x03R\fcommentCount\x12%\n" +
	"\x0ebookmark_count\x18\x04 \x01(\x03R\rbookmarkCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x05 \x01(\x03R\tviewCount\x12\x19\n" +
	"\bis_liked\x18\x06 \x01(\bR\aisLiked\x12#\n" +
	"\ris_bookmarked\x18\a \x01(\bR\fisBookmarked2\xdd\x01\n" +
	"\x12InteractionService\x12]\n" +
	"\x13GetVideoInteraction\x12'.interaction.GetVideoInteractionRequest\x1a\x1d.interaction.VideoInteraction\x12h\n" +
	"\x13GetBulkInteractions\x12'.interaction.GetBulkInteractionsRequest\x1a(.interaction.GetBulkInteractionsResponseBq\n" +
	"\x1bcom.kiseki.interaction.grpcB\x10InteractionProtoP\x01Z;github.com/kiseki/video-service/internal/grpc/interactionpb\x90\x01\x01b\x06proto3"

var (
	file_interaction_proto_rawDescOnce sync.Once
	file_interaction_proto_rawDescData []byte
)

func file_interaction_proto_rawDescGZIP() []byte {
	file_interaction_proto_rawDescOnce.Do(func() {
		file_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)))
	})
	return file_interaction_proto_rawDescData
}

var file_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_interaction_proto_goTypes = []any{
	(*GetVideoInteractionRequest)(nil),  // 0: interaction.GetVideoInteractionRequest
	(*GetBulkInteractionsRequest)(nil),  // 1: interaction.GetBulkInteractionsRequest
	(*GetBulkInteractionsResponse)(nil), // 2: interaction.GetBulkInteractionsResponse
	(*VideoInteraction)(nil),            // 3: interaction.VideoInteraction
}
var file_interaction_proto_depIdxs = []int32{
	3, // 0: interaction.GetBulkInteractionsResponse.interactions:type_name -> interaction.VideoInteraction
	0, // 1: interaction.InteractionService.GetVideoInteraction:input_type -> interaction.GetVideoInteractionRequest
	1, // 2: interaction.InteractionService.GetBulkInteractions:input_type -> interaction.GetBulkInteractionsRequest
	3, // 3: interaction.InteractionService.GetVideoInteraction:output_type -> interaction.VideoInteraction
	2, // 4: interaction.InteractionService.GetBulkInteractions:output_type -> interaction.GetBulkInteractionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_interaction_proto_init() }
func file_interaction_proto_init() {
	if File_interaction_proto != nil {
		return
	}
	file_interaction_proto_msgTypes[0].OneofWrappers = []any{}
	file_interaction_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_proto_rawDesc), len(file_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_proto_depIdxs,
		MessageInfos:      file_interaction_proto_msgTypes,
	}.Build()
	File_interaction_proto = out.File
	file_interaction_proto_goTypes = nil
	file_interaction_proto_depIdxs = nil
}
