# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"#\n\x12GetTrendingRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\";\n\x13GetTrendingResponse\x12$\n\x06videos\x18\x01 \x03(\x0b\x32\x14.event.TrendingVideo\"k\n\rTrendingVideo\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\ncategories\x18\x03 \x03(\t\x12\x10\n\x08hashtags\x18\x04 \x03(\t\x12\x13\n\x0bwatch_count\x18\x05 \x01(\x03\x32Z\n\x0c\x45ventService\x12J\n\x11GetTrendingVideos\x12\x19.event.GetTrendingRequest\x1a\x1a.event.GetTrendingResponseBCZ+github.com/kiseki/event-service/proto/event\xaa\x02\x13\x45ventService.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/kiseki/event-service/proto/event\252\002\023EventService.Protos'
  _globals['_GETTRENDINGREQUEST']._serialized_start=22
  _globals['_GETTRENDINGREQUEST']._serialized_end=57
  _globals['_GETTRENDINGRESPONSE']._serialized_start=59
  _globals['_GETTRENDINGRESPONSE']._serialized_end=118
  _globals['_TRENDINGVIDEO']._serialized_start=120
  _globals['_TRENDINGVIDEO']._serialized_end=227
  _globals['_EVENTSERVICE']._serialized_start=229
  _globals['_EVENTSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
