# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'interaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11interaction.proto\x12\x0binteraction\"Q\n\x1aGetBulkInteractionsRequest\x12\x11\n\tvideo_ids\x18\x01 \x03(\t\x12\x14\n\x07user_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_user_id\"R\n\x1bGetBulkInteractionsResponse\x12\x33\n\x0cinteractions\x18\x01 \x03(\x0b\x32\x1d.interaction.VideoInteraction\"\xa4\x01\n\x10VideoInteraction\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x12\n\nlike_count\x18\x02 \x01(\x03\x12\x15\n\rcomment_count\x18\x03 \x01(\x03\x12\x16\n\x0e\x62ookmark_count\x18\x04 \x01(\x03\x12\x12\n\nview_count\x18\x05 \x01(\x03\x12\x10\n\x08is_liked\x18\x06 \x01(\x08\x12\x15\n\ris_bookmarked\x18\x07 \x01(\x08\x32~\n\x12InteractionService\x12h\n\x13GetBulkInteractions\x12\'.interaction.GetBulkInteractionsRequest\x1a(.interaction.GetBulkInteractionsResponseB4\n\x1b\x63om.kiseki.interaction.grpcB\x10InteractionProtoP\x01\x90\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.kiseki.interaction.grpcB\020InteractionProtoP\001\220\001\001'
  _globals['_GETBULKINTERACTIONSREQUEST']._serialized_start=34
  _globals['_GETBULKINTERACTIONSREQUEST']._serialized_end=115
  _globals['_GETBULKINTERACTIONSRESPONSE']._serialized_start=117
  _globals['_GETBULKINTERACTIONSRESPONSE']._serialized_end=199
  _globals['_VIDEOINTERACTION']._serialized_start=202
  _globals['_VIDEOINTERACTION']._serialized_end=366
  _globals['_INTERACTIONSERVICE']._serialized_start=368
  _globals['_INTERACTIONSERVICE']._serialized_end=494
_builder.BuildServices(DESCRIPTOR, 'interaction_pb2', _globals)
# @@protoc_insertion_point(module_scope)
