# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"\xe0\x01\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x03 \x01(\t\x12,\n\x04type\x18\x04 \x01(\x0e\x32\x1e.notification.NotificationType\x12\x15\n\x08video_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x17\n\ncomment_id\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07is_read\x18\x07 \x01(\x08\x12\x12\n\ncreated_at\x18\x08 \x01(\x03\x42\x0b\n\t_video_idB\r\n\x0b_comment_id\"K\n\x17GetNotificationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"\x98\x01\n\x18GetNotificationsResponse\x12\x31\n\rnotifications\x18\x01 \x03(\x0b\x32\x1a.notification.Notification\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x05 \x01(\x05\">\n\x11MarkAsReadRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x18\n\x10notification_ids\x18\x02 \x03(\t\"6\n\x12MarkAsReadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x15GetUnreadCountRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\".\n\x16GetUnreadCountResponse\x12\x14\n\x0cunread_count\x18\x01 \x01(\x05*C\n\x10NotificationType\x12\x08\n\x04LIKE\x10\x00\x12\x0b\n\x07\x43OMMENT\x10\x01\x12\n\n\x06\x46OLLOW\x10\x02\x12\x0c\n\x08\x42OOKMARK\x10\x03\x32\xa6\x02\n\x13NotificationService\x12\x61\n\x10GetNotifications\x12%.notification.GetNotificationsRequest\x1a&.notification.GetNotificationsResponse\x12O\n\nMarkAsRead\x12\x1f.notification.MarkAsReadRequest\x1a .notification.MarkAsReadResponse\x12[\n\x0eGetUnreadCount\x12#.notification.GetUnreadCountRequest\x1a$.notification.GetUnreadCountResponseBN\n\x1c\x63om.kiseki.notification.grpcB\x11NotificationProtoP\x01\xaa\x02\x18NotificationService.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.kiseki.notification.grpcB\021NotificationProtoP\001\252\002\030NotificationService.Grpc'
  _globals['_NOTIFICATIONTYPE']._serialized_start=705
  _globals['_NOTIFICATIONTYPE']._serialized_end=772
  _globals['_NOTIFICATION']._serialized_start=37
  _globals['_NOTIFICATION']._serialized_end=261
  _globals['_GETNOTIFICATIONSREQUEST']._serialized_start=263
  _globals['_GETNOTIFICATIONSREQUEST']._serialized_end=338
  _globals['_GETNOTIFICATIONSRESPONSE']._serialized_start=341
  _globals['_GETNOTIFICATIONSRESPONSE']._serialized_end=493
  _globals['_MARKASREADREQUEST']._serialized_start=495
  _globals['_MARKASREADREQUEST']._serialized_end=557
  _globals['_MARKASREADRESPONSE']._serialized_start=559
  _globals['_MARKASREADRESPONSE']._serialized_end=613
  _globals['_GETUNREADCOUNTREQUEST']._serialized_start=615
  _globals['_GETUNREADCOUNTREQUEST']._serialized_end=655
  _globals['_GETUNREADCOUNTRESPONSE']._serialized_start=657
  _globals['_GETUNREADCOUNTRESPONSE']._serialized_end=703
  _globals['_NOTIFICATIONSERVICE']._serialized_start=775
  _globals['_NOTIFICATIONSERVICE']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
