# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"$\n\x11VerifyUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"5\n\x12VerifyUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"\xbc\x01\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\x12\x0b\n\x03\x62io\x18\x05 \x01(\t\x12\x19\n\x11profile_image_url\x18\x06 \x01(\t\x12\x17\n\x0f\x66ollowers_count\x18\x07 \x01(\x03\x12\x17\n\x0f\x66ollowing_count\x18\x08 \x01(\x03\x12\x12\n\ncreated_at\x18\t \x01(\t2\x86\x01\n\x0bUserService\x12?\n\nVerifyUser\x12\x17.user.VerifyUserRequest\x1a\x18.user.VerifyUserResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponseBm\n\x14\x63om.kiseki.user.grpcB\tUserProtoP\x01Z3github.com/kiseki/user-service/internal/grpc/userpb\xaa\x02\x12UserService.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.kiseki.user.grpcB\tUserProtoP\001Z3github.com/kiseki/user-service/internal/grpc/userpb\252\002\022UserService.Protos'
  _globals['_VERIFYUSERREQUEST']._serialized_start=20
  _globals['_VERIFYUSERREQUEST']._serialized_end=56
  _globals['_VERIFYUSERRESPONSE']._serialized_start=58
  _globals['_VERIFYUSERRESPONSE']._serialized_end=111
  _globals['_GETUSERREQUEST']._serialized_start=113
  _globals['_GETUSERREQUEST']._serialized_end=146
  _globals['_GETUSERRESPONSE']._serialized_start=148
  _globals['_GETUSERRESPONSE']._serialized_end=191
  _globals['_USER']._serialized_start=194
  _globals['_USER']._serialized_end=382
  _globals['_USERSERVICE']._serialized_start=385
  _globals['_USERSERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
