# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"\'\n\x13GetVideoByIdRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"3\n\x14GetVideoByIdResponse\x12\x1b\n\x05video\x18\x01 \x01(\x0b\x32\x0c.video.Video\"#\n\x0fGetVideoRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"/\n\x10GetVideoResponse\x12\x1b\n\x05video\x18\x01 \x01(\x0b\x32\x0c.video.Video\"1\n\x10GetVideosRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"1\n\x11GetVideosResponse\x12\x1c\n\x06videos\x18\x01 \x03(\x0b\x32\x0c.video.Video\"\xc1\x01\n\x05Video\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x12\n\ncategories\x18\x04 \x03(\t\x12\x10\n\x08hashtags\x18\x05 \x03(\t\x12 \n\x05owner\x18\x06 \x01(\x0b\x32\x11.video.VideoOwner\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x15\n\rthumbnail_url\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\x03\"\xa7\x01\n\nVideoOwner\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x19\n\x11profile_image_url\x18\x04 \x01(\t\x12\x17\n\x0f\x66ollowers_count\x18\x05 \x01(\x03\x12\x17\n\x0f\x66ollowing_count\x18\x06 \x01(\x03\x12\x13\n\x0bis_verified\x18\x07 \x01(\x08\x32\x8b\x01\n\x0cVideoService\x12;\n\x08GetVideo\x12\x16.video.GetVideoRequest\x1a\x17.video.GetVideoResponse\x12>\n\tGetVideos\x12\x17.video.GetVideosRequest\x1a\x18.video.GetVideosResponseBr\n\x15\x63om.kiseki.video.grpcB\nVideoProtoP\x01Z5github.com/kiseki/video-service/internal/grpc/videopb\xaa\x02\x13VideoService.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.kiseki.video.grpcB\nVideoProtoP\001Z5github.com/kiseki/video-service/internal/grpc/videopb\252\002\023VideoService.Protos'
  _globals['_GETVIDEOBYIDREQUEST']._serialized_start=22
  _globals['_GETVIDEOBYIDREQUEST']._serialized_end=61
  _globals['_GETVIDEOBYIDRESPONSE']._serialized_start=63
  _globals['_GETVIDEOBYIDRESPONSE']._serialized_end=114
  _globals['_GETVIDEOREQUEST']._serialized_start=116
  _globals['_GETVIDEOREQUEST']._serialized_end=151
  _globals['_GETVIDEORESPONSE']._serialized_start=153
  _globals['_GETVIDEORESPONSE']._serialized_end=200
  _globals['_GETVIDEOSREQUEST']._serialized_start=202
  _globals['_GETVIDEOSREQUEST']._serialized_end=251
  _globals['_GETVIDEOSRESPONSE']._serialized_start=253
  _globals['_GETVIDEOSRESPONSE']._serialized_end=302
  _globals['_VIDEO']._serialized_start=305
  _globals['_VIDEO']._serialized_end=498
  _globals['_VIDEOOWNER']._serialized_start=501
  _globals['_VIDEOOWNER']._serialized_end=668
  _globals['_VIDEOSERVICE']._serialized_start=671
  _globals['_VIDEOSERVICE']._serialized_end=810
# @@protoc_insertion_point(module_scope)
