# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import video_pb2 as video__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in video_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideo = channel.unary_unary(
                '/video.VideoService/GetVideo',
                request_serializer=video__pb2.GetVideoRequest.SerializeToString,
                response_deserializer=video__pb2.GetVideoResponse.FromString,
                _registered_method=True)
        self.GetVideos = channel.unary_unary(
                '/video.VideoService/GetVideos',
                request_serializer=video__pb2.GetVideosRequest.SerializeToString,
                response_deserializer=video__pb2.GetVideosResponse.FromString,
                _registered_method=True)


class VideoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideo(self, request, context):
        """Get details of a single video (alias for backward compatibility)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideos(self, request, context):
        """Get a batch of videos (for feed)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideo,
                    request_deserializer=video__pb2.GetVideoRequest.FromString,
                    response_serializer=video__pb2.GetVideoResponse.SerializeToString,
            ),
            'GetVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideos,
                    request_deserializer=video__pb2.GetVideosRequest.FromString,
                    response_serializer=video__pb2.GetVideosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video.VideoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('video.VideoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/GetVideo',
            video__pb2.GetVideoRequest.SerializeToString,
            video__pb2.GetVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/video.VideoService/GetVideos',
            video__pb2.GetVideosRequest.SerializeToString,
            video__pb2.GetVideosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
