// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/stream.proto

package streampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type GetStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_proto_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *GetStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *Stream                `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamResponse) Reset() {
	*x = GetStreamResponse{}
	mi := &file_proto_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamResponse) ProtoMessage() {}

func (x *GetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamResponse.ProtoReflect.Descriptor instead.
func (*GetStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *GetStreamResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

type GetStreamByKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamKey     string                 `protobuf:"bytes,1,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamByKeyRequest) Reset() {
	*x = GetStreamByKeyRequest{}
	mi := &file_proto_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamByKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamByKeyRequest) ProtoMessage() {}

func (x *GetStreamByKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamByKeyRequest.ProtoReflect.Descriptor instead.
func (*GetStreamByKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *GetStreamByKeyRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type GetStreamByKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *Stream                `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamByKeyResponse) Reset() {
	*x = GetStreamByKeyResponse{}
	mi := &file_proto_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamByKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamByKeyResponse) ProtoMessage() {}

func (x *GetStreamByKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamByKeyResponse.ProtoReflect.Descriptor instead.
func (*GetStreamByKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{3}
}

func (x *GetStreamByKeyResponse) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

type GetLiveStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveStreamsRequest) Reset() {
	*x = GetLiveStreamsRequest{}
	mi := &file_proto_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveStreamsRequest) ProtoMessage() {}

func (x *GetLiveStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveStreamsRequest.ProtoReflect.Descriptor instead.
func (*GetLiveStreamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{4}
}

func (x *GetLiveStreamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLiveStreamsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLiveStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*Stream              `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiveStreamsResponse) Reset() {
	*x = GetLiveStreamsResponse{}
	mi := &file_proto_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiveStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiveStreamsResponse) ProtoMessage() {}

func (x *GetLiveStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiveStreamsResponse.ProtoReflect.Descriptor instead.
func (*GetLiveStreamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{5}
}

func (x *GetLiveStreamsResponse) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *GetLiveStreamsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStreamsRequest) Reset() {
	*x = GetUserStreamsRequest{}
	mi := &file_proto_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStreamsRequest) ProtoMessage() {}

func (x *GetUserStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStreamsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStreamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserStreamsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserStreamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserStreamsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetUserStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*Stream              `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStreamsResponse) Reset() {
	*x = GetUserStreamsResponse{}
	mi := &file_proto_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStreamsResponse) ProtoMessage() {}

func (x *GetUserStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStreamsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStreamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserStreamsResponse) GetStreams() []*Stream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *GetUserStreamsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateStreamStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "offline", "live", "ending"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamStatusRequest) Reset() {
	*x = UpdateStreamStatusRequest{}
	mi := &file_proto_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamStatusRequest) ProtoMessage() {}

func (x *UpdateStreamStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStreamStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStreamStatusRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *UpdateStreamStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStreamStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStreamStatusResponse) Reset() {
	*x = UpdateStreamStatusResponse{}
	mi := &file_proto_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStreamStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStreamStatusResponse) ProtoMessage() {}

func (x *UpdateStreamStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStreamStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStreamStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStreamStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStreamStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatsRequest) Reset() {
	*x = GetStreamStatsRequest{}
	mi := &file_proto_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsRequest) ProtoMessage() {}

func (x *GetStreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamStatsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetStreamStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *StreamStats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatsResponse) Reset() {
	*x = GetStreamStatsResponse{}
	mi := &file_proto_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsResponse) ProtoMessage() {}

func (x *GetStreamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStreamStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{11}
}

func (x *GetStreamStatsResponse) GetStats() *StreamStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Data models
type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,3,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "offline", "live", "ending"
	ViewerCount   int64                  `protobuf:"varint,8,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	StartedAt     int64                  `protobuf:"varint,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`  // Unix timestamp
	EndedAt       int64                  `protobuf:"varint,10,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`       // Unix timestamp
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	SaveVod       bool                   `protobuf:"varint,13,opt,name=save_vod,json=saveVod,proto3" json:"save_vod,omitempty"`
	Owner         *StreamOwner           `protobuf:"bytes,14,opt,name=owner,proto3" json:"owner,omitempty"` // Optional user info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_proto_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{12}
}

func (x *Stream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stream) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Stream) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *Stream) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Stream) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Stream) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Stream) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Stream) GetViewerCount() int64 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *Stream) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Stream) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *Stream) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Stream) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Stream) GetSaveVod() bool {
	if x != nil {
		return x.SaveVod
	}
	return false
}

func (x *Stream) GetOwner() *StreamOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type StreamOwner struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,4,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	IsVerified      bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamOwner) Reset() {
	*x = StreamOwner{}
	mi := &file_proto_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOwner) ProtoMessage() {}

func (x *StreamOwner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOwner.ProtoReflect.Descriptor instead.
func (*StreamOwner) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{13}
}

func (x *StreamOwner) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamOwner) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StreamOwner) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *StreamOwner) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *StreamOwner) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type StreamStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ViewerCount     int64                  `protobuf:"varint,2,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	PeakViewers     int64                  `protobuf:"varint,3,opt,name=peak_viewers,json=peakViewers,proto3" json:"peak_viewers,omitempty"`
	TotalViewers    int64                  `protobuf:"varint,4,opt,name=total_viewers,json=totalViewers,proto3" json:"total_viewers,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AverageBitrate  float64                `protobuf:"fixed64,6,opt,name=average_bitrate,json=averageBitrate,proto3" json:"average_bitrate,omitempty"`
	VideoPackets    int64                  `protobuf:"varint,7,opt,name=video_packets,json=videoPackets,proto3" json:"video_packets,omitempty"`
	AudioPackets    int64                  `protobuf:"varint,8,opt,name=audio_packets,json=audioPackets,proto3" json:"audio_packets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamStats) Reset() {
	*x = StreamStats{}
	mi := &file_proto_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStats) ProtoMessage() {}

func (x *StreamStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStats.ProtoReflect.Descriptor instead.
func (*StreamStats) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{14}
}

func (x *StreamStats) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamStats) GetViewerCount() int64 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *StreamStats) GetPeakViewers() int64 {
	if x != nil {
		return x.PeakViewers
	}
	return 0
}

func (x *StreamStats) GetTotalViewers() int64 {
	if x != nil {
		return x.TotalViewers
	}
	return 0
}

func (x *StreamStats) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StreamStats) GetAverageBitrate() float64 {
	if x != nil {
		return x.AverageBitrate
	}
	return 0
}

func (x *StreamStats) GetVideoPackets() int64 {
	if x != nil {
		return x.VideoPackets
	}
	return 0
}

func (x *StreamStats) GetAudioPackets() int64 {
	if x != nil {
		return x.AudioPackets
	}
	return 0
}

var File_proto_stream_proto protoreflect.FileDescriptor

const file_proto_stream_proto_rawDesc = "" +
	"\n" +
	"\x12proto/stream.proto\x12\x06stream\"/\n" +
	"\x10GetStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\";\n" +
	"\x11GetStreamResponse\x12&\n" +
	"\x06stream\x18\x01 \x01(\v2\x0e.stream.StreamR\x06stream\"6\n" +
	"\x15GetStreamByKeyRequest\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x01 \x01(\tR\tstreamKey\"@\n" +
	"\x16GetStreamByKeyResponse\x12&\n" +
	"\x06stream\x18\x01 \x01(\v2\x0e.stream.StreamR\x06stream\"E\n" +
	"\x15GetLiveStreamsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"c\n" +
	"\x16GetLiveStreamsResponse\x12(\n" +
	"\astreams\x18\x01 \x03(\v2\x0e.stream.StreamR\astreams\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"^\n" +
	"\x15GetUserStreamsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"c\n" +
	"\x16GetUserStreamsResponse\x12(\n" +
	"\astreams\x18\x01 \x03(\v2\x0e.stream.StreamR\astreams\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"P\n" +
	"\x19UpdateStreamStatusRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"P\n" +
	"\x1aUpdateStreamStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x15GetStreamStatsRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"C\n" +
	"\x16GetStreamStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x01(\v2\x13.stream.StreamStatsR\x05stats\"\xa6\x03\n" +
	"\x06Stream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x03 \x01(\tR\tstreamKey\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fviewer_count\x18\b \x01(\x03R\vviewerCount\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\n" +
	" \x01(\x03R\aendedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x19\n" +
	"\bsave_vod\x18\r \x01(\bR\asaveVod\x12)\n" +
	"\x05owner\x18\x0e \x01(\v2\x13.stream.StreamOwnerR\x05owner\"\xb2\x01\n" +
	"\vStreamOwner\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12*\n" +
	"\x11profile_image_url\x18\x04 \x01(\tR\x0fprofileImageUrl\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\"\xb3\x02\n" +
	"\vStreamStats\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\fviewer_count\x18\x02 \x01(\x03R\vviewerCount\x12!\n" +
	"\fpeak_viewers\x18\x03 \x01(\x03R\vpeakViewers\x12#\n" +
	"\rtotal_viewers\x18\x04 \x01(\x03R\ftotalViewers\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x03R\x0fdurationSeconds\x12'\n" +
	"\x0faverage_bitrate\x18\x06 \x01(\x01R\x0eaverageBitrate\x12#\n" +
	"\rvideo_packets\x18\a \x01(\x03R\fvideoPackets\x12#\n" +
	"\raudio_packets\x18\b \x01(\x03R\faudioPackets2\xf2\x03\n" +
	"\rStreamService\x12@\n" +
	"\tGetStream\x12\x18.stream.GetStreamRequest\x1a\x19.stream.GetStreamResponse\x12O\n" +
	"\x0eGetStreamByKey\x12\x1d.stream.GetStreamByKeyRequest\x1a\x1e.stream.GetStreamByKeyResponse\x12O\n" +
	"\x0eGetLiveStreams\x12\x1d.stream.GetLiveStreamsRequest\x1a\x1e.stream.GetLiveStreamsResponse\x12O\n" +
	"\x0eGetUserStreams\x12\x1d.stream.GetUserStreamsRequest\x1a\x1e.stream.GetUserStreamsResponse\x12[\n" +
	"\x12UpdateStreamStatus\x12!.stream.UpdateStreamStatusRequest\x1a\".stream.UpdateStreamStatusResponse\x12O\n" +
	"\x0eGetStreamStats\x12\x1d.stream.GetStreamStatsRequest\x1a\x1e.stream.GetStreamStatsResponseBz\n" +
	"\x16com.kiseki.stream.grpcB\vStreamProtoP\x01Z7github.com/kiseki/stream-service/internal/grpc/streampb\x90\x01\x01\xaa\x02\x14StreamService.Protosb\x06proto3"

var (
	file_proto_stream_proto_rawDescOnce sync.Once
	file_proto_stream_proto_rawDescData []byte
)

func file_proto_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)))
	})
	return file_proto_stream_proto_rawDescData
}

var file_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_stream_proto_goTypes = []any{
	(*GetStreamRequest)(nil),           // 0: stream.GetStreamRequest
	(*GetStreamResponse)(nil),          // 1: stream.GetStreamResponse
	(*GetStreamByKeyRequest)(nil),      // 2: stream.GetStreamByKeyRequest
	(*GetStreamByKeyResponse)(nil),     // 3: stream.GetStreamByKeyResponse
	(*GetLiveStreamsRequest)(nil),      // 4: stream.GetLiveStreamsRequest
	(*GetLiveStreamsResponse)(nil),     // 5: stream.GetLiveStreamsResponse
	(*GetUserStreamsRequest)(nil),      // 6: stream.GetUserStreamsRequest
	(*GetUserStreamsResponse)(nil),     // 7: stream.GetUserStreamsResponse
	(*UpdateStreamStatusRequest)(nil),  // 8: stream.UpdateStreamStatusRequest
	(*UpdateStreamStatusResponse)(nil), // 9: stream.UpdateStreamStatusResponse
	(*GetStreamStatsRequest)(nil),      // 10: stream.GetStreamStatsRequest
	(*GetStreamStatsResponse)(nil),     // 11: stream.GetStreamStatsResponse
	(*Stream)(nil),                     // 12: stream.Stream
	(*StreamOwner)(nil),                // 13: stream.StreamOwner
	(*StreamStats)(nil),                // 14: stream.StreamStats
}
var file_proto_stream_proto_depIdxs = []int32{
	12, // 0: stream.GetStreamResponse.stream:type_name -> stream.Stream
	12, // 1: stream.GetStreamByKeyResponse.stream:type_name -> stream.Stream
	12, // 2: stream.GetLiveStreamsResponse.streams:type_name -> stream.Stream
	12, // 3: stream.GetUserStreamsResponse.streams:type_name -> stream.Stream
	14, // 4: stream.GetStreamStatsResponse.stats:type_name -> stream.StreamStats
	13, // 5: stream.Stream.owner:type_name -> stream.StreamOwner
	0,  // 6: stream.StreamService.GetStream:input_type -> stream.GetStreamRequest
	2,  // 7: stream.StreamService.GetStreamByKey:input_type -> stream.GetStreamByKeyRequest
	4,  // 8: stream.StreamService.GetLiveStreams:input_type -> stream.GetLiveStreamsRequest
	6,  // 9: stream.StreamService.GetUserStreams:input_type -> stream.GetUserStreamsRequest
	8,  // 10: stream.StreamService.UpdateStreamStatus:input_type -> stream.UpdateStreamStatusRequest
	10, // 11: stream.StreamService.GetStreamStats:input_type -> stream.GetStreamStatsRequest
	1,  // 12: stream.StreamService.GetStream:output_type -> stream.GetStreamResponse
	3,  // 13: stream.StreamService.GetStreamByKey:output_type -> stream.GetStreamByKeyResponse
	5,  // 14: stream.StreamService.GetLiveStreams:output_type -> stream.GetLiveStreamsResponse
	7,  // 15: stream.StreamService.GetUserStreams:output_type -> stream.GetUserStreamsResponse
	9,  // 16: stream.StreamService.UpdateStreamStatus:output_type -> stream.UpdateStreamStatusResponse
	11, // 17: stream.StreamService.GetStreamStats:output_type -> stream.GetStreamStatsResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_stream_proto_init() }
func file_proto_stream_proto_init() {
	if File_proto_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_proto_depIdxs,
		MessageInfos:      file_proto_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_proto = out.File
	file_proto_stream_proto_goTypes = nil
	file_proto_stream_proto_depIdxs = nil
}
