// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/stream.proto

package streampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_GetStream_FullMethodName          = "/stream.StreamService/GetStream"
	StreamService_GetStreamByKey_FullMethodName     = "/stream.StreamService/GetStreamByKey"
	StreamService_GetLiveStreams_FullMethodName     = "/stream.StreamService/GetLiveStreams"
	StreamService_GetUserStreams_FullMethodName     = "/stream.StreamService/GetUserStreams"
	StreamService_UpdateStreamStatus_FullMethodName = "/stream.StreamService/UpdateStreamStatus"
	StreamService_GetStreamStats_FullMethodName     = "/stream.StreamService/GetStreamStats"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	// Get stream by ID
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamResponse, error)
	// Get stream by stream key (for authentication)
	GetStreamByKey(ctx context.Context, in *GetStreamByKeyRequest, opts ...grpc.CallOption) (*GetStreamByKeyResponse, error)
	// Get all live streams
	GetLiveStreams(ctx context.Context, in *GetLiveStreamsRequest, opts ...grpc.CallOption) (*GetLiveStreamsResponse, error)
	// Get user's streams
	GetUserStreams(ctx context.Context, in *GetUserStreamsRequest, opts ...grpc.CallOption) (*GetUserStreamsResponse, error)
	// Update stream status (internal use)
	UpdateStreamStatus(ctx context.Context, in *UpdateStreamStatusRequest, opts ...grpc.CallOption) (*UpdateStreamStatusResponse, error)
	// Get stream statistics
	GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*GetStreamStatsResponse, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetStreamByKey(ctx context.Context, in *GetStreamByKeyRequest, opts ...grpc.CallOption) (*GetStreamByKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamByKeyResponse)
	err := c.cc.Invoke(ctx, StreamService_GetStreamByKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetLiveStreams(ctx context.Context, in *GetLiveStreamsRequest, opts ...grpc.CallOption) (*GetLiveStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveStreamsResponse)
	err := c.cc.Invoke(ctx, StreamService_GetLiveStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetUserStreams(ctx context.Context, in *GetUserStreamsRequest, opts ...grpc.CallOption) (*GetUserStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStreamsResponse)
	err := c.cc.Invoke(ctx, StreamService_GetUserStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) UpdateStreamStatus(ctx context.Context, in *UpdateStreamStatusRequest, opts ...grpc.CallOption) (*UpdateStreamStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStreamStatusResponse)
	err := c.cc.Invoke(ctx, StreamService_UpdateStreamStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*GetStreamStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamStatsResponse)
	err := c.cc.Invoke(ctx, StreamService_GetStreamStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
type StreamServiceServer interface {
	// Get stream by ID
	GetStream(context.Context, *GetStreamRequest) (*GetStreamResponse, error)
	// Get stream by stream key (for authentication)
	GetStreamByKey(context.Context, *GetStreamByKeyRequest) (*GetStreamByKeyResponse, error)
	// Get all live streams
	GetLiveStreams(context.Context, *GetLiveStreamsRequest) (*GetLiveStreamsResponse, error)
	// Get user's streams
	GetUserStreams(context.Context, *GetUserStreamsRequest) (*GetUserStreamsResponse, error)
	// Update stream status (internal use)
	UpdateStreamStatus(context.Context, *UpdateStreamStatusRequest) (*UpdateStreamStatusResponse, error)
	// Get stream statistics
	GetStreamStats(context.Context, *GetStreamStatsRequest) (*GetStreamStatsResponse, error)
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) GetStream(context.Context, *GetStreamRequest) (*GetStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedStreamServiceServer) GetStreamByKey(context.Context, *GetStreamByKeyRequest) (*GetStreamByKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamByKey not implemented")
}
func (UnimplementedStreamServiceServer) GetLiveStreams(context.Context, *GetLiveStreamsRequest) (*GetLiveStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLiveStreams not implemented")
}
func (UnimplementedStreamServiceServer) GetUserStreams(context.Context, *GetUserStreamsRequest) (*GetUserStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStreams not implemented")
}
func (UnimplementedStreamServiceServer) UpdateStreamStatus(context.Context, *UpdateStreamStatusRequest) (*UpdateStreamStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStreamStatus not implemented")
}
func (UnimplementedStreamServiceServer) GetStreamStats(context.Context, *GetStreamStatsRequest) (*GetStreamStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamStats not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetStreamByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStreamByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetStreamByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStreamByKey(ctx, req.(*GetStreamByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetLiveStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetLiveStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetLiveStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetLiveStreams(ctx, req.(*GetLiveStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetUserStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetUserStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetUserStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetUserStreams(ctx, req.(*GetUserStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_UpdateStreamStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStreamStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).UpdateStreamStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_UpdateStreamStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).UpdateStreamStatus(ctx, req.(*UpdateStreamStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetStreamStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStreamStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetStreamStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStreamStats(ctx, req.(*GetStreamStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStream",
			Handler:    _StreamService_GetStream_Handler,
		},
		{
			MethodName: "GetStreamByKey",
			Handler:    _StreamService_GetStreamByKey_Handler,
		},
		{
			MethodName: "GetLiveStreams",
			Handler:    _StreamService_GetLiveStreams_Handler,
		},
		{
			MethodName: "GetUserStreams",
			Handler:    _StreamService_GetUserStreams_Handler,
		},
		{
			MethodName: "UpdateStreamStatus",
			Handler:    _StreamService_UpdateStreamStatus_Handler,
		},
		{
			MethodName: "GetStreamStats",
			Handler:    _StreamService_GetStreamStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stream.proto",
}
